# messages/config.yaml
# Kafka Config
kafka:
  brokers:
    - "goletan-broker-name-1"
    - "goletan-broker-name-2"
  topic: "goletan-topic-name"
  group_id: "goletan-group-id"
  batch_size: 100
  retries: 3
  timeout: 10
  compression: "snappy"
  offset: "earliest"

# DLQ Config
dlq:
  brokers:
    - "goletan-broker-name-1"
    - "goletan-broker-name-2"
  topic: "goletan-topic-name"
  compression: "snappy"
